apiVersion: v1
kind: Service
metadata:
  name: dotnet-k8s-api
  namespace: dotnet-k8s-api
spec:
  type: ClusterIP
  selector:
    app: dotnet-k8s-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
